### ISSUE TITLE
Request path contains unescaped characters

### ISSUE THREAD

**Issue by radum** [smebberson/gulp-electron-downloader#1]
If you are behind a proxy server this will fail with:

```
Request path contains unescaped characters
```

This is because there is a bug in the `tunnel-agent` module. Module used by `request` which is used by `github-releases` which is used by this module.

I've opened a ticket on `github-releases` to updated the request version but I don't think this will happen any time soon.

Do you really need to use `github-releases`?

**Comment by smebberson** [comment]
I'm not actually using `github-releases`, just `request`. I'm using `request` v2.55.0 though, does the issue exist in that version?

**Comment by radum** [comment]
:grinning: actually this was supposed to be for another project. I wonder what was in my head when I posted it here. Sorry this can be closed.

PS: And yes request 2.55 works great behind proxies.

**Comment by smebberson** [comment]
No worries, all good.
